name: jazzy-devel

on:
  pull_request:
    branches:
      - jazzy-devel
  push:
    branches:
      - jazzy-devel
  workflow_dispatch:
    schedule:
      - cron: '0 0 * * 0'
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.9
        with:
          required-ros-distributions: jazzy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: rclcpp_cascade_lifecycle rclcpy_cascade_lifecycle cascade_lifecycle_msgs
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: ""
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
